language: php

os:
- linux

stages:
- name: Test Workflow

branches:
  only:
  - master
  except:
  - develop

php:
  - '7.3'
  - '7.4'

before_script:
  - composer install
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit

